In [ ]:
## here i will generate the input for bypass from the vcf file generates by slim

In [65]:
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as stats
import math 
import os

import allel
import subprocess

In [66]:
allele_counts_slim_full_cov = pd.read_csv('allele_counts_slim_full_cov.csv').set_index('Unnamed: 0')

In [67]:
allele_counts_slim_full_cov

,ref_subp0,alt_subp0,ref_subp1,alt_subp1,ref_subp2,alt_subp2,ref_subp3,alt_subp3,ref_subp4,alt_subp4,...,ref_subp11,alt_subp11,ref_subp12,alt_subp12,ref_subp13,alt_subp13,ref_subp14,alt_subp14,ref_subp15,alt_subp15
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
6063,162.0,838.0,134.0,866.0,141.0,859.0,119.0,881.0,239.0,293.0,...,117.0,883.0,68.0,932.0,146.0,854.0,23.0,883.0,283.0,717.0
13538,520.0,480.0,462.0,538.0,318.0,682.0,528.0,472.0,259.0,273.0,...,430.0,570.0,92.0,908.0,485.0,515.0,245.0,661.0,662.0,338.0
19532,208.0,792.0,260.0,740.0,157.0,843.0,132.0,868.0,239.0,293.0,...,177.0,823.0,68.0,932.0,276.0,724.0,123.0,783.0,438.0,562.0
19931,975.0,25.0,840.0,160.0,911.0,89.0,906.0,94.0,NaN,NaN,...,838.0,162.0,689.0,311.0,866.0,134.0,894.0,12.0,945.0,55.0
23006,974.0,26.0,825.0,175.0,881.0,119.0,972.0,28.0,NaN,NaN,...,999.0,1.0,876.0,124.0,936.0,64.0,NaN,NaN,882.0,118.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28167692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,982.0,18.0
30057156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,982.0,18.0
30065201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,982.0,18.0
30325819,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,982.0,18.0
30394571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,982.0,18.0

In [68]:
subps = allele_counts_slim_full_cov.columns

In [69]:
subps = [i for i in subps if 'ref_' in i]

In [70]:
pool_size = []
for subp in subps:
    leng = len(allele_counts_slim_full_cov[subp].dropna())
    pool_size.append(leng)

In [71]:
#.str.replace('ref_', '')
subps = [i.replace('ref_', '') for i in subps]

In [72]:
pool_size = pd.Series(pool_size, subps)

In [73]:
pool_size.loc['subp0']

4972

In [78]:
allele_counts_slim_full_cov.columns

Index(['ref_subp0', 'alt_subp0', 'ref_subp1', 'alt_subp1', 'ref_subp2',
       'alt_subp2', 'ref_subp3', 'alt_subp3', 'ref_subp4', 'alt_subp4',
       'ref_subp5', 'alt_subp5', 'ref_subp6', 'alt_subp6', 'ref_subp7',
       'alt_subp7', 'ref_subp8', 'alt_subp8', 'ref_subp9', 'alt_subp9',
       'ref_subp10', 'alt_subp10', 'ref_subp11', 'alt_subp11', 'ref_subp12',
       'alt_subp12', 'ref_subp13', 'alt_subp13', 'ref_subp14', 'alt_subp14',
       'ref_subp15', 'alt_subp15'],
      dtype='object')

In [79]:
for col in allele_counts_slim_full_cov.columns:
    if 'ref_' in col: 
        allele_counts_slim_full_cov.loc[:,col] = allele_counts_slim_full_cov.loc[:, col].fillna(pool_size.loc[col[4:]])
    else:
        allele_counts_slim_full_cov.loc[:,col] = allele_counts_slim_full_cov.loc[:, col].fillna(0)

In [80]:
allele_counts_slim_full_cov

,ref_subp0,alt_subp0,ref_subp1,alt_subp1,ref_subp2,alt_subp2,ref_subp3,alt_subp3,ref_subp4,alt_subp4,...,ref_subp11,alt_subp11,ref_subp12,alt_subp12,ref_subp13,alt_subp13,ref_subp14,alt_subp14,ref_subp15,alt_subp15
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
6063,162.0,838.0,134.0,866.0,141.0,859.0,119.0,881.0,239.0,293.0,...,117.0,883.0,68.0,932.0,146.0,854.0,23.0,883.0,283.0,717.0
13538,520.0,480.0,462.0,538.0,318.0,682.0,528.0,472.0,259.0,273.0,...,430.0,570.0,92.0,908.0,485.0,515.0,245.0,661.0,662.0,338.0
19532,208.0,792.0,260.0,740.0,157.0,843.0,132.0,868.0,239.0,293.0,...,177.0,823.0,68.0,932.0,276.0,724.0,123.0,783.0,438.0,562.0
19931,975.0,25.0,840.0,160.0,911.0,89.0,906.0,94.0,2770.0,0.0,...,838.0,162.0,689.0,311.0,866.0,134.0,894.0,12.0,945.0,55.0
23006,974.0,26.0,825.0,175.0,881.0,119.0,972.0,28.0,2770.0,0.0,...,999.0,1.0,876.0,124.0,936.0,64.0,3499.0,0.0,882.0,118.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28167692,4972.0,0.0,5335.0,0.0,5422.0,0.0,5458.0,0.0,2770.0,0.0,...,5749.0,0.0,4788.0,0.0,5034.0,0.0,3499.0,0.0,982.0,18.0
30057156,4972.0,0.0,5335.0,0.0,5422.0,0.0,5458.0,0.0,2770.0,0.0,...,5749.0,0.0,4788.0,0.0,5034.0,0.0,3499.0,0.0,982.0,18.0
30065201,4972.0,0.0,5335.0,0.0,5422.0,0.0,5458.0,0.0,2770.0,0.0,...,5749.0,0.0,4788.0,0.0,5034.0,0.0,3499.0,0.0,982.0,18.0
30325819,4972.0,0.0,5335.0,0.0,5422.0,0.0,5458.0,0.0,2770.0,0.0,...,5749.0,0.0,4788.0,0.0,5034.0,0.0,3499.0,0.0,982.0,18.0
30394571,4972.0,0.0,5335.0,0.0,5422.0,0.0,5458.0,0.0,2770.0,0.0,...,5749.0,0.0,4788.0,0.0,5034.0,0.0,3499.0,0.0,982.0,18.0

In [99]:
allele_counts_slim_full_cov = allele_counts_slim_full_cov.astype(int)

In [100]:
allele_counts_slim_full_cov.to_csv('baypass/geno_table_slim', header=None, sep = ' ', index=False)

In [94]:
# double the pool size because it is asking for number of chromosomes 
pool_size = pool_size * 2

In [96]:
pd.DataFrame(pool_size).T.to_csv('baypass/pool_size_slim', header=None, sep = ' ', index=False)